import type { Metadata } from "next";
import { Rye, Libre_Bodoni, Nunito_Sans } from "next/font/google";
import "./globals.css";

const rye_init = Rye({
  subsets: ['latin'],
  variable: "--font-rye",
  weight: "400",
});

const libre_bodoni_init = Libre_Bodoni({
  subsets: ['latin'],
  variable: "--font-libre-bodoni",
  weight: ["400","500","600","700"]
});

const nunito_sans_init = Nunito_Sans({
  subsets: ['latin'],
  variable: "--font-nunito-sans",
  weight: ["200", "300", "400","500","600","700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rye_init.variable} ${libre_bodoni_init.variable} ${nunito_sans_init.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
